CREATE TABLE CLIENTE (
    CPF VARCHAR (11) NOT NULL,
    dataNasc DATE NOT NULL,
    sexo CHAR (1),
    endereço VARCHAR (30) NOT NULL,
    nome VARCHAR (30),
    PRIMARY KEY (CPF)
);
CREATE TABLE PEDIDO (
    idPedido INT NOT NULL AUTO_INCREMENT,
    idCliente VARCHAR (11) NOT NULL,
    dataInclusão DATE NOT NULL,
    endereçoEntrega VARCHAR (30) NOT NULL,
    PRIMARY KEY (idPedido),
    FOREIGN KEY (idCliente) REFERENCES CLIENTE (CPF)
);
CREATE TABLE TRANSPORTADORA (
    CNPJ VARCHAR (14) NOT NULL,
    ID INT NOT NULL AUTO_INCREMENT,
    endereço VARCHAR (30) NOT NULL,
    nome VARCHAR (15) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (CNPJ)
);
CREATE TABLE ENTREGA (
    ID INT NOT NULL AUTO_INCREMENT,
    dataEntrega DATE NOT NULL,
    CNPJ VARCHAR (14) NOT NULL,
    custoTranporte FLOAT,
    idRastreamento INT NOT NULL,
    pedidoID INT NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (CNPJ) REFERENCES TRANSPORTADORA (CNPJ),
    FOREIGN KEY (idRastreamento) REFERENCES TRANSPORTADORA (ID),
    FOREIGN KEY (pedidoID) REFERENCES PEDIDO (idPedido)
);
CREATE TABLE DEVOLUÇÃO (
    codDevolução INT NOT NULL AUTO_INCREMENT,
    pedidoCod INT NOT NULL,
    descrição VARCHAR (30) NOT NULL,
    PRIMARY KEY (codDevolução),
    FOREIGN KEY (pedidoCod) REFERENCES PEDIDO (idPedido) 
);
